/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_contact_final;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author kenfack
 */
public class Fagent extends javax.swing.JFrame {

    String code="1";
    String nom="k";
    String date="1" ;
    String address="m";
    String email="k";
    int numero=2;
    int salaire=1;
    String  statut="n";
    String categorie="m";
    int indsal=6;
    String occupation="m";
    
    
    public Fagent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        v_code = new javax.swing.JTextField();
        v_nom = new javax.swing.JTextField();
        v_email = new javax.swing.JTextField();
        v_address = new javax.swing.JTextField();
        v_date = new javax.swing.JTextField();
        v_numero = new javax.swing.JTextField();
        v_salaire = new javax.swing.JTextField();
        v_categorie = new javax.swing.JTextField();
        v_indsal = new javax.swing.JTextField();
        v_occupation = new javax.swing.JTextField();
        choix = new javax.swing.JComboBox<>();
        v_enregistre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("        FORMULAIRE AGENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("CODE");

        jLabel3.setText("NOM");

        jLabel4.setText("DATE NES");

        jLabel5.setText("ADDRESS");

        jLabel6.setText("EMAIL");

        jLabel7.setText("NUMERO TEL");

        jLabel8.setText("SALAIRE");

        jLabel9.setText("STATUT");

        jLabel10.setText("INDICE SALAIRE");

        jLabel11.setText("CATEGORIE");

        jLabel12.setText("OCCUPATION");

        v_code.setText("1");
        v_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_codeActionPerformed(evt);
            }
        });

        v_nom.setText("kf");
        v_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_nomActionPerformed(evt);
            }
        });

        v_email.setText("kf.cm");
        v_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_emailActionPerformed(evt);
            }
        });

        v_address.setText("ya");
        v_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_addressActionPerformed(evt);
            }
        });

        v_date.setText("12/12/01");
        v_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_dateActionPerformed(evt);
            }
        });

        v_numero.setText("674");
        v_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_numeroActionPerformed(evt);
            }
        });

        v_salaire.setText("100");
        v_salaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_salaireActionPerformed(evt);
            }
        });

        v_categorie.setText("mk");
        v_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_categorieActionPerformed(evt);
            }
        });

        v_indsal.setText("1");
        v_indsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_indsalActionPerformed(evt);
            }
        });

        v_occupation.setText("test");
        v_occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_occupationActionPerformed(evt);
            }
        });

        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "temporaire", "stagaire", "permanent" }));
        choix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixActionPerformed(evt);
            }
        });

        v_enregistre.setText("enregistrer");
        v_enregistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_enregistreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(30, 30, 30)
                                        .addComponent(v_date, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(v_address)
                                            .addComponent(v_nom)
                                            .addComponent(v_code)
                                            .addComponent(v_email, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v_salaire)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(choix, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(v_categorie)
                                    .addComponent(v_indsal)
                                    .addComponent(v_occupation))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(v_enregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(v_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(v_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(v_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(v_indsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(v_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(v_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(v_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(v_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(v_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(v_enregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_codeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_codeActionPerformed

    private void v_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_nomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_nomActionPerformed

    private void v_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_addressActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_addressActionPerformed

    private void v_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_emailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_emailActionPerformed

    private void v_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_dateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_dateActionPerformed

    private void v_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_numeroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_numeroActionPerformed

    private void v_salaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_salaireActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_salaireActionPerformed

    private void choixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_choixActionPerformed

    private void v_categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_categorieActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_categorieActionPerformed

    private void v_indsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_indsalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_v_indsalActionPerformed

    private void v_occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_occupationActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_v_occupationActionPerformed
   
    private void v_enregistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_enregistreActionPerformed
        code=v_code.getText();
        nom=v_nom.getText();
        nom=v_nom.getText();
        address=v_address.getText();
        date=v_date.getText();
        email=v_email.getText();
        numero=Integer.parseInt(v_numero.getText());
        salaire=Integer.parseInt(v_salaire.getText());
        statut =(String)choix.getSelectedItem();
        categorie= v_categorie.getText();
        indsal=Integer.parseInt(v_indsal.getText());
        occupation=v_occupation.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/personne?useSSL=false", "root", "noumedem");

            // Insertion
            String insertionQuery = "INSERT INTO Agent (Salaire,Statut,Categorie,ind_sal,occupation,code,nom,date_de_naissance,address,email,telNumber) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            try (PreparedStatement insertionStatement = con.prepareStatement(insertionQuery)) {
                
                insertionStatement.setInt(1, salaire);
                insertionStatement.setString(2, statut);
                insertionStatement.setString(3, categorie);
                insertionStatement.setInt(4, indsal);
                insertionStatement.setString(5, occupation);
                insertionStatement.setString(6, code);
                insertionStatement.setString(7, nom);
                insertionStatement.setString(8, date);
                insertionStatement.setString(9, address);
                insertionStatement.setString(10, email);
                insertionStatement.setInt(11, numero);
                
                insertionStatement.executeUpdate();
                System.out.println("Insertion successful.");
            } catch (SQLException ex) {
                System.out.println("Insertion error: " + ex.getMessage());
            }

          

            con.close();
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
        System.out.println("Valeur de code: " + code);
        System.out.println("Valeur de nom: " + nom);
        System.out.println("Valeur de date: " + date);
        System.out.println("Valeur de address: " + address);
        System.out.println("Valeur de email: " + email);
        System.out.println("Valeur de numero: " + numero);
        System.out.println("Valeur de salaire: " + salaire);
        System.out.println("Valeur de statut: " + statut);
        System.out.println("Valeur de categorie: " + categorie);
        System.out.println("Valeur de indsal: " + indsal);
        System.out.println("Valeur de occupation: " + occupation);
        
    }//GEN-LAST:event_v_enregistreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fagent().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField v_address;
    private javax.swing.JTextField v_categorie;
    private javax.swing.JTextField v_code;
    private javax.swing.JTextField v_date;
    private javax.swing.JTextField v_email;
    private javax.swing.JButton v_enregistre;
    private javax.swing.JTextField v_indsal;
    private javax.swing.JTextField v_nom;
    private javax.swing.JTextField v_numero;
    private javax.swing.JTextField v_occupation;
    private javax.swing.JTextField v_salaire;
    // End of variables declaration//GEN-END:variables
}
